<?php

namespace Database\Seeders;

class ImportSextoPrincipalSeeder extends ImportPreescolarPrincipalSeeder
{
    public function run(): void
    {
        $rows = [
            [
                'estudiante' => 'ALTAMIRANDA DAGER MATIAS DE JESUS',
                'tipo_doc_estudiante' => 'TI',
                'doc_estudiante' => '1050970389',
                'acudiente' => 'JORAINE DAGER',
                'doc_acudiente' => '1143376179',
                'telefono' => '3205597258',
            ],
            [
                'estudiante' => 'BALLESTAS MARTINEZ KEVIN ANDRES',
                'tipo_doc_estudiante' => 'TI',
                'doc_estudiante' => '1201241173',
                'acudiente' => 'ANGELICA MARIA MARTINEZ GARCIA',
                'doc_acudiente' => '33226470',
                'telefono' => '3008283350',
            ],
            [
                'estudiante' => 'BRAVO BRAN MELANY',
                'tipo_doc_estudiante' => 'TI',
                'doc_estudiante' => '1023533281',
                'acudiente' => 'AURA CRISTINA BRAN BERRIO',
                'doc_acudiente' => '1022098016',
                'telefono' => '3155020819',
            ],
            [
                'estudiante' => 'CANEDO PAEZ THIAGO DAVID',
                'tipo_doc_estudiante' => 'TI',
                'doc_estudiante' => '1124412384',
                'acudiente' => 'LIZBETH LEONOR PAEZ RAMIREZ',
                'doc_acudiente' => '1124401780',
                'telefono' => '3165222764',
            ],
            [
                'estudiante' => 'CARDENAS URANGO SAMUEL DAVID',
                'tipo_doc_estudiante' => 'TI',
                'doc_estudiante' => '1043320565',
                'acudiente' => 'YESENIA INES URANGO SIBAJA',
                'doc_acudiente' => '23175405',
                'telefono' => '3015566976',
            ],
            [
                'estudiante' => 'CASTILLO ACOSTA NAOMI ALESSANDRA',
                'tipo_doc_estudiante' => 'PPT',
                'doc_estudiante' => '6282154',
                'acudiente' => 'KEILA DILIMAR ACOSTA TALAVERA',
                'doc_acudiente' => '6178904',
                'telefono' => '3215756162',
            ],
            [
                'estudiante' => 'CHAMORRO ROMERO MAICK ESTEBAN',
                'tipo_doc_estudiante' => 'TI',
                'doc_estudiante' => '1044000007',
                'acudiente' => 'MAIRA ALEJANDRA ROMERO AMARIZO',
                'doc_acudiente' => '45759839',
                'telefono' => '3135438419',
            ],
            [
                'estudiante' => 'DE HOYOS FRANCO SAMUEL DAVID',
                'tipo_doc_estudiante' => 'TI',
                'doc_estudiante' => '1201241887',
                'acudiente' => 'MAYRA FRANCO CASTRO',
                'doc_acudiente' => '1143118756',
                'telefono' => '3002118038',
            ],
            [
                'estudiante' => 'GONZALEZ DE LA HOZ JULIAN ANDRES',
                'tipo_doc_estudiante' => 'TI',
                'doc_estudiante' => '1043319579',
                'acudiente' => 'MERIETH DEL CARMEN DE LA HOZ ZULBARAN',
                'doc_acudiente' => '45548659',
                'telefono' => '3006649278',
            ],
            [
                'estudiante' => 'GONZALEZ PADILLA DOMINICK',
                'tipo_doc_estudiante' => 'TI',
                'doc_estudiante' => '1043993877',
                'acudiente' => 'OMARYS DEL CARMEN PADILLA JASPE',
                'doc_acudiente' => '1047414154',
                'telefono' => '3022155515',
            ],
            [
                'estudiante' => 'GUERRERO LARA DARIEL JOSE',
                'tipo_doc_estudiante' => 'TI',
                'doc_estudiante' => '1044000400',
                'acudiente' => 'KEVIN JOSE GUERRERO BERRIO',
                'doc_acudiente' => '1047414077',
                'telefono' => '3207337399',
            ],
            [
                'estudiante' => 'LOPEZ MALO MATIAS DAVID',
                'tipo_doc_estudiante' => 'TI',
                'doc_estudiante' => '1201246880',
                'acudiente' => 'YURANIS MALO RODRIGUEZ',
                'doc_acudiente' => '1128045640',
                'telefono' => '3004005675',
            ],
            [
                'estudiante' => 'LOPEZ NEGRETE ALEJANDRO MANUEL',
                'tipo_doc_estudiante' => 'TI',
                'doc_estudiante' => '1138029587',
                'acudiente' => 'CINDY ROCIO NEGRETE ARROYAVE',
                'doc_acudiente' => '1138029587',
                'telefono' => '3145813615',
            ],
            [
                'estudiante' => 'MALDONADO DEL RIO ROBERTO JESUS',
                'tipo_doc_estudiante' => 'TI',
                'doc_estudiante' => '1041993239',
                'acudiente' => 'ROSEMARY DEL RIO CABARCAS',
                'doc_acudiente' => '22804938',
                'telefono' => '3175140782',
            ],
            [
                'estudiante' => 'MARTINEZ CASTELLAR LUIS ANGEL',
                'tipo_doc_estudiante' => 'TI',
                'doc_estudiante' => '1142943415',
                'acudiente' => 'LIVIVET CASTELLAR ALGARIN',
                'doc_acudiente' => '32907338',
                'telefono' => '3244010447',
            ],
            [
                'estudiante' => 'MENDOZA PEREZ SERGIO LUIS',
                'tipo_doc_estudiante' => 'TI',
                'doc_estudiante' => '1143396401',
                'acudiente' => 'MARYS DEL MAR PEREZ MORELO',
                'doc_acudiente' => '33333094',
                'telefono' => '3046217590',
            ],
            [
                'estudiante' => 'MIRA ALMARIO MARTIN DE JESUS',
                'tipo_doc_estudiante' => 'TI',
                'doc_estudiante' => '1201239684',
                'acudiente' => 'LIDIS MARIA ALMARIO VILLADIEGO',
                'doc_acudiente' => '45368895',
                'telefono' => '3158240541',
            ],
            [
                'estudiante' => 'MIRA ALMARIO SALVATORE JOSUE',
                'tipo_doc_estudiante' => 'TI',
                'doc_estudiante' => '1201239685',
                'acudiente' => 'LIDIS MARIA ALMARIO VILLADIEGO',
                'doc_acudiente' => '45368895',
                'telefono' => '3158240541',
            ],
            [
                'estudiante' => 'MORALES HERNANDEZ DYLAN DAVID',
                'tipo_doc_estudiante' => 'TI',
                'doc_estudiante' => '1043321010',
                'acudiente' => 'MIRAMA MARTINEZ HERNANDEZ',
                'doc_acudiente' => '45761366',
                'telefono' => '3014668971',
            ],
            [
                'estudiante' => 'OSPINO PEREZ SAMUEL DAVID',
                'tipo_doc_estudiante' => 'TI',
                'doc_estudiante' => '1201237957',
                'acudiente' => 'DIANA OSPINO',
                'doc_acudiente' => '1001936719',
                'telefono' => '3226340184',
            ],
            [
                'estudiante' => 'PENA MERCADO LEDIS GABRIELA',
                'tipo_doc_estudiante' => 'TI',
                'doc_estudiante' => '1201240483',
                'acudiente' => 'GREISY MERCADO VILLADIEGO',
                'doc_acudiente' => '1047454780',
                'telefono' => '3174129561',
            ],
            [
                'estudiante' => 'SIMANCA CABALLERO GENESIS',
                'tipo_doc_estudiante' => 'TI',
                'doc_estudiante' => '1201243956',
                'acudiente' => 'ANA MARIA CABALLERO',
                'doc_acudiente' => '55245799',
                'telefono' => '3011833179',
            ],
            [
                'estudiante' => 'MUNOZ MEZA MATIAS DAVID',
                'tipo_doc_estudiante' => 'TI',
                'doc_estudiante' => '1142943960',
                'acudiente' => 'YULYS PAOLA MEZA DE HOYOS',
                'doc_acudiente' => '1067403413',
                'telefono' => '3106711998',
            ],
        ];

        $this->importDataset($rows, [
            'nombre' => 'Sexto A',
            'nivel' => 'bachillerato',
            'grado' => '6°',
            'grupo' => 'A',
            'jornada' => 'mañana',
        ]);
    }
}
